model : 'MobileViT'
dataset_name : 'ImageNet_1k'
classes : 1000
data_path : '/mnt'
save_dir : './saved'
gpus : -1

input_size : 256

workers : 4
epochs : 1000
batch_size : 16

save_freq : 5

varient : 's'

optimizer : 'sgd'
optimizer_options:
  lr : 3e-3
  nesterov : true
  momentum : 0.9
  weight_decay : 1e-5

trainer_options:
  check_val_every_n_epoch : 5